import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SidebarComponent from "@/components/dashboard/SidebarComponent";
import StoreProvider from "@/app/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className="flex">
      <StoreProvider>
          <aside className="h-screen">
              <SidebarComponent/>
          </aside>
          <main className="flex-1">
              <section>
                  {children}
              </section>
          </main>
      </StoreProvider>
      </body>
      </html>
  )
}
